#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${1:-$ROOT_DIR/.env.docker}"
OUTPUT_FILE="${2:-$ROOT_DIR/configs/config.docker.generated.yaml}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

SERVER_HOST="${SERVER_HOST:-0.0.0.0}"
SERVER_PORT="${SERVER_PORT:-18080}"
SERVER_PUBLIC_HOST="${SERVER_PUBLIC_HOST:-localhost}"
PUBLIC_GATEWAY_PORT="${GATEWAY_PORT:-8080}"
SERVER_PUBLIC_PORT="${SERVER_PUBLIC_PORT:-$PUBLIC_GATEWAY_PORT}"
SERVER_PUBLIC_BASE_URL="${SERVER_PUBLIC_BASE_URL:-http://localhost:$SERVER_PUBLIC_PORT}"
SERVER_MEDIA_PUBLIC_BASE_URL="${SERVER_MEDIA_PUBLIC_BASE_URL:-$SERVER_PUBLIC_BASE_URL}"

MYSQL_DATABASE="${MYSQL_DATABASE:-music_users}"
MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-change_me_please}"
REDIS_PASSWORD="${REDIS_PASSWORD:-}"

DB_SCHEMA_PROFILE="${DB_SCHEMA_PROFILE:-music_profile}"
DB_SCHEMA_CATALOG="${DB_SCHEMA_CATALOG:-music_users}"
DB_SCHEMA_MEDIA="${DB_SCHEMA_MEDIA:-music_media}"
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-admin123456}"
ADMIN_SESSION_TTL_MINUTES="${ADMIN_SESSION_TTL_MINUTES:-1440}"

yaml_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat > "$OUTPUT_FILE" <<YAML
# This file is generated by scripts/docker/render_config.sh. Do not edit manually.
server:
  host: "$(yaml_escape "$SERVER_HOST")"
  port: ${SERVER_PORT}
  public_host: "$(yaml_escape "$SERVER_PUBLIC_HOST")"
  public_port: ${SERVER_PUBLIC_PORT}
  public_base_url: "$(yaml_escape "$SERVER_PUBLIC_BASE_URL")"
  media_public_base_url: "$(yaml_escape "$SERVER_MEDIA_PUBLIC_BASE_URL")"
  static_dir: ""
  upload_dir: "/data/uploads"
  video_dir: "/data/video"
  video_hls_dir: "/data/video_hls"
  ffmpeg_binary: "ffmpeg"
  ffprobe_binary: "ffprobe"
  enable_tls: false
  cert_file: ""
  key_file: ""

database:
  host: "mysql"
  port: 3306
  user: "root"
  password: "$(yaml_escape "$MYSQL_ROOT_PASSWORD")"
  name: "$(yaml_escape "$MYSQL_DATABASE")"

redis:
  host: "redis"
  port: 6379
  password: "$(yaml_escape "$REDIS_PASSWORD")"

event:
  bus:
    stream: "music.domain.events.v1"
    group: "music-domain-events-group"
    consumer: ""
    pending_min_idle_ms: 30000
    pending_batch_size: 50
  outbox:
    poll_interval_ms: 2000
    batch_size: 50
    max_retry: 10
    retry_base_delay_ms: 1000
  worker:
    max_retry: 3
    retry_delay_ms: 300

schemas:
  profile: "$(yaml_escape "$DB_SCHEMA_PROFILE")"
  catalog: "$(yaml_escape "$DB_SCHEMA_CATALOG")"
  media: "$(yaml_escape "$DB_SCHEMA_MEDIA")"

external:
  jamendo:
    enabled: true
    client_id: ""
    base_url: "https://api.jamendo.com/v3.0"
    timeout_sec: 8
    default_limit: 20

admin:
  username: "$(yaml_escape "$ADMIN_USERNAME")"
  password: "$(yaml_escape "$ADMIN_PASSWORD")"
  session_ttl_minutes: ${ADMIN_SESSION_TTL_MINUTES}
YAML

echo "Generated: $OUTPUT_FILE"
